In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import re
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
# key => 
# 산업안전보건법 + "1"
# 건설기술진흥법 + "2"
# 위험물안전관리법 + '3'
# 전기안전관리법 + "4"
# 화학물질관리법 + "5"

In [4]:
df_info = pd.read_excel("전체법.xlsx")

In [2]:
# 불용어 리스트
# 불용어, 불필요 단어 제거
stop_words_df = pd.read_excel("stopwords.xlsx")
stop_words_df

      불용어
0       아
1       휴
2     아이구
3     아이쿠
4     아이고
..    ...
694    따른
695   필요한
696    등을
697  해당하는
698    자가

[699 rows x 1 columns]

In [5]:
posts = df_info.get("조내용")
posts_key = df_info.get("키")
key = [i for i in posts_key]
posts

0      제1조(목적) 이 법은 산업 안전 및 보건에 관한 기준을 확립하고 그 책임의 소재를...
1      제2조(정의) 이 법에서 사용하는 용어의 뜻은 다음과 같다. <개정 2020.5.2...
2      제3조(적용 범위) 이 법은 모든 사업에 적용한다. 다만, 유해ㆍ위험의 정도, 사업...
3      제4조(정부의 책무) 정부는 이 법의 목적을 달성하기 위하여 다음 각 호의 사항을 ...
4      제5조(사업주 등의 의무) 사업주(제77조에 따른 특수형태근로종사자로부터 노무를 제...
                             ...
452    제60조(벌칙) 제43조제2항에 따라 즉시 신고를 하지 아니한 자는 2년 이하의 징...
453    제61조(벌칙) 다음 각 호의 어느 하나에 해당하는 자는 1년 이하의 징역 또는 3...
454    제62조(벌칙) 다음 각 호의 어느 하나에 해당하는 자는 6개월 이하의 징역 또는 ...
455    제63조(양벌규정) 법인의 대표자나 법인 또는 개인의 대리인, 사용인, 그 밖의 종...
456    제64조(과태료) 다음 각 호의 어느 하나에 해당하는 자에게는 1천만원 이하의 과태...
Name: 조내용, Length: 457, dtype: object

In [31]:
def get_key(**key) :
    dic = {}
    for k, y in key.items():
        if k[-1] == "1" :
            s = "OSH"+k[0:(len(k)-4)]
        elif k[-1]=="2":
            s = "CTP"+k[0:(len(k)-4)]
        elif k[-1]=="3":
            s = "HSM"+k[0:(len(k)-4)]
        elif k[-1]=="4":
            s = "ESM"+k[0:(len(k)-4)]
        elif k[-1]=="5":
            s = "CMM"+k[0:(len(k)-4)]
        if k[-3] != "0":
            s += "의 "+k[-3]   
        dic[s] = y
    return dic

In [7]:
from konlpy.tag import Okt
okt = Okt()

oo = okt.pos(posts[0],
        norm=True,   # 정규화(normalization)
        stem=True    # 어간추출(stemming)
        )
print(oo)

[('제', 'Noun'), ('1조', 'Number'), ('(', 'Punctuation'), ('목적', 'Noun'), (')', 'Punctuation'), ('이', 'Noun'), ('법', 'Noun'), ('은', 'Josa'), ('산업', 'Noun'), ('안전', 'Noun'), ('및', 'Noun'), ('보건', 'Noun'), ('에', 'Josa'), ('관', 'Noun'), ('한', 'Josa'), ('기준', 'Noun'), ('을', 'Josa'), ('확립', 'Noun'), ('하고', 'Josa'), ('그', 'Noun'), ('책임', 'Noun'), ('의', 'Josa'), ('소재', 'Noun'), ('를', 'Josa'), ('명확하다', 'Adjective'), ('하다', 'Verb'), ('산업', 'Noun'), ('재해', 'Noun'), ('를', 'Josa'), ('예방', 'Noun'), ('하고', 'Josa'), ('쾌적하다', 'Adjective'), ('작업', 'Noun'), ('환경', 'Noun'), ('을', 'Josa'), ('조', 'Modifier'), ('성함', 'Noun'), ('으로써', 'Josa'), ('노무', 'Noun'), ('를', 'Josa'), ('제공', 'Noun'), ('하다', 'Verb'), ('사람', 'Noun'), ('의', 'Josa'), ('안전', 'Noun'), ('및', 'Noun'), ('보건', 'Noun'), ('을', 'Josa'), ('유지', 'Noun'), ('ㆍ', 'Foreign'), ('증진', 'Noun'), ('함', 'Noun'), ('을', 'Josa'), ('목적', 'Noun'), ('으로', 'Josa'), ('하다', 'Verb'), ('.', 'Punctuation'), ('<', 'Punctuation'), ('개정', 'Noun'), ('2020.5', 'Number'), ('.', 'Punctuation'), ('26', 'Number'), ('>', 'Punctuation')]

In [12]:
def tokenizer_1(raw_texts, pos=["Noun","Alpha","Verb","Number"], stop_words=list(stop_words_df.get("불용어"))):
    p = okt.pos(raw_texts, 
            norm=True,   # 정규화(normalization)
            stem=True    # 어간추출(stemming)
            )
    o = [word for word, tag in p if len(word) > 1 and tag in pos and word[0] not in stop_words]
    return(o)

tokenizer_1(posts[80])

['81조',
 '기계',
 '기구',
 '대통령령',
 '기계',
 '기구',
 '설비',
 '건축물',
 '타인',
 '대여',
 '거나',
 '대여받다',
 '안전',
 '보건']

In [13]:
from konlpy.tag import Mecab
tagger = Mecab()
# from eunjeon import Mecab
# tagger = Mecab()
def tokenizer_2(raw_texts, pos=["Noun","Alpha","Verb","Number"], stop_words=list(stop_words_df.get("불용어"))):
    nouns = []
  
    for noun in tagger.nouns(raw_texts):
        if noun not in stop_words:
            nouns.append(noun)
    return nouns

tokenizer_2(posts[80])

['기계', '대여자', '조치', '기계', '건축물', '대여', '필요', '안전', '조치', '보건', '조치']

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorize = TfidfVectorizer(
    tokenizer=tokenizer_1, # 문장에 대한 tokenizer (위에 정의한 함수 이용)
    min_df=1,            # 단어가 출현하는 최소 문서의 개수
    sublinear_tf=True,    # tf값에 1+log(tf)를 적용하여 tf값이 무한정 커지는 것을 막음
    stop_words= list(stop_words_df.get("불용어"))
)

X = vectorize.fit_transform(posts)
X.toarray()

/opt/anaconda3/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:383: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['갖다', '거리', '견지', '결과', '결론', '고려', '공동', '관계', '관련', '근거', '기대', '기점', '기준', '까닭', '낫다', '누가', '다시', '달다', '대로', '대하', '대해', '더불다', '더욱이', '도달', '도착', '동시', '돼다', '되다', '되어다', '두번째', '뒤따르다', '따다', '따르다', '따름', '라면', '리하', '마자', '막론', '만이', '만큼', '만하', '말다', '망정', '몰랏다', '무릎', '바꾸다', '반대', '방면', '보다', '보아', '본대', '부류', '불구', '불문', '비걱거리', '비교', '비기다', '비추다', '상대', '생각', '서술', '시오', '시작', '시초', '쓰다', '쓰이다', '안다', '않다', '알다', '연관', '울다', '위해', '입다', '입장', '잇따르다', '정도', '종합', '주저', '즈음', '지경', '지다', '진짜', '차다', '켜다', '크다', '틈타다', '편이', '한적', '해도', '해보다', '형식'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# TFID(Euclidean Distance)

In [15]:
# 모든 조에 해당하는 euclidean distance 를 계산
euclidean_result = []
for x in range(len(df_info)):
    tmp = []
    for y in range(len(df_info)):
        tmp.append(euclidean_distances(X[x], X[y])[0][0])
    euclidean_result.append(tmp)
# euclidean_result

In [16]:
# 모든 조에 해당하는 euclidean distance 결과 값을
# DataFrame 형태로 변환
euclidean_result_df = pd.DataFrame(euclidean_result)
euclidean_result_df

,0,1,2,3,4,5,6,7,8,9,...,447,448,449,450,451,452,453,454,455,456
0,0.000000,1.296081,1.414214,1.189069,1.267283,1.366741,1.380620,1.380410,1.343451,1.369181,...,1.376270,1.389387,1.414214,1.403902,1.385119,1.414214,1.409636,1.409038,1.414214,1.409101
1,1.296081,0.000000,1.317738,1.342317,1.236590,1.280926,1.334705,1.351841,1.364561,1.220271,...,1.381510,1.383463,1.401336,1.386336,1.386370,1.412620,1.387091,1.395705,1.400448,1.380559
2,1.414214,1.317738,0.000000,1.414214,1.374448,1.379677,1.414214,1.406493,1.414214,1.396049,...,1.414214,1.278349,1.414214,1.393036,1.397011,1.414214,1.398924,1.404024,1.414214,1.395851
3,1.189069,1.342317,1.414214,0.000000,1.325462,1.274056,1.363372,1.300893,1.273204,1.382720,...,1.269711,1.313836,1.414214,1.401562,1.375773,1.410842,1.398192,1.405574,1.390531,1.398812
4,1.267283,1.236590,1.374448,1.325462,0.000000,1.185763,1.377182,1.361381,1.352376,1.341500,...,1.388946,1.397028,1.414214,1.362994,1.350549,1.408538,1.367748,1.373908,1.404245,1.398238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,1.414214,1.412620,1.414214,1.410842,1.408538,1.403145,1.407932,1.408287,1.406390,1.407566,...,1.404535,1.374238,1.311241,1.296239,1.357540,0.000000,1.287919,1.328463,1.414214,1.367844
453,1.409636,1.387091,1.398924,1.398192,1.367748,1.390617,1.362420,1.387567,1.405308,1.395836,...,1.399491,1.389018,1.342829,1.032127,1.230607,1.287919,0.000000,1.054040,1.414214,1.068457
454,1.409038,1.395705,1.404024,1.405574,1.373908,1.406684,1.390222,1.390059,1.408889,1.402213,...,1.403452,1.386561,1.373718,1.132337,1.215693,1.328463,1.054040,0.000000,1.369031,1.215651
455,1.414214,1.400448,1.414214,1.390531,1.404245,1.392100,1.414214,1.386392,1.414214,1.414214,...,1.402777,1.392851,1.349541,1.376493,1.350554,1.414214,1.414214,1.369031,0.000000,1.388957
456,1.409101,1.380559,1.395851,1.398812,1.398238,1.371794,1.367725,1.383248,1.396971,1.362478,...,1.390806,1.375845,1.414214,1.155074,1.158889,1.367844,1.068457,1.215651,1.388957,0.000000

In [32]:
# euclidean distance 값으로 
# 24조와 가장 비슷한 조를 찾기위한 과정
jo_key = 240011
jo = key.index(jo_key)
y_euclidean = euclidean_result_df[jo]
dic = {}
for i in range(len(y_euclidean)):
    dic[str(posts_key[i])] = y_euclidean[i]
dic = get_key(**dic)
#8조와 비슷한 조 찾기 위함
# euclidean distance 를 dic에 씌워 sorting 함(1부터 10위까지)
sorted(dic.items(), key=lambda x: x[1])[0:15]

[('OSH24', 0.0),
 ('OSH25', 18.384776310850235),
 ('OSH49', 18.547236990991408),
 ('OSH32', 19.157244060668017),
 ('OSH35', 19.672315572906),
 ('OSH26', 19.82422760159901),
 ('OSH4', 20.0),
 ('OSH19', 20.0),
 ('OSH31', 20.808652046684813),
 ('OSH50', 20.808652046684813),
 ('OSH29', 21.142374511865974),
 ('OSH37', 21.142374511865974),
 ('OSH44', 21.354156504062622),
 ('OSH22', 21.470910553583888),
 ('OSH20', 21.517434791350013)]

# TFID(Cosine Similarity)

In [18]:
cosine_result = []
for x in range(len(df_info)):
    tmp = []
    for y in range(len(df_info)):
        tmp.append(cosine_similarity(X[x], X[y])[0][0])
    cosine_result.append(tmp)

In [20]:
# 모든 조에 해당하는 cosine similarity 결과 값을
# DataFrame 형태로 변환
cosine_result_df = pd.DataFrame(cosine_result)
cosine_result_df

,0,1,2,3,4,5,6,7,8,9,...,447,448,449,450,451,452,453,454,455,456
0,1.000000,0.160086,0.000000,0.293057,0.196996,0.066010,0.046944,0.047235,0.097570,0.062671,...,0.052940,0.034801,0.000000,0.014529,0.040722,0.000000,0.006463,0.007306,0.000000,0.007217
1,0.160086,1.000000,0.131784,0.099092,0.235423,0.179614,0.109281,0.086262,0.068987,0.255470,...,0.045715,0.043015,0.018129,0.039036,0.038989,0.002252,0.037990,0.026004,0.019372,0.047029
2,0.000000,0.131784,1.000000,0.000000,0.055446,0.048245,0.000000,0.010888,0.000000,0.025524,...,0.000000,0.182912,0.000000,0.029726,0.024180,0.000000,0.021506,0.014359,0.000000,0.025800
3,0.293057,0.099092,0.000000,1.000000,0.121575,0.188391,0.070609,0.153839,0.189475,0.044042,...,0.193916,0.136917,0.000000,0.017812,0.053624,0.004763,0.022529,0.012181,0.033211,0.021662
4,0.196996,0.235423,0.055446,0.121575,1.000000,0.296984,0.051685,0.073321,0.085540,0.100189,...,0.035415,0.024156,0.000000,0.071123,0.088008,0.008010,0.064633,0.056189,0.014048,0.022465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,0.000000,0.002252,0.000000,0.004763,0.008010,0.015592,0.008863,0.008364,0.011034,0.009380,...,0.013640,0.055734,0.140323,0.159883,0.078542,1.000000,0.170633,0.117593,0.000000,0.064501
453,0.006463,0.037990,0.021506,0.022529,0.064633,0.033093,0.071906,0.037329,0.012554,0.025821,...,0.020713,0.035314,0.098405,0.467357,0.242804,0.170633,1.000000,0.444499,0.000000,0.429200
454,0.007306,0.026004,0.014359,0.012181,0.056189,0.010620,0.033641,0.033868,0.007516,0.016900,...,0.015162,0.038725,0.056450,0.358906,0.261045,0.117593,0.444499,1.000000,0.062877,0.261096
455,0.000000,0.019372,0.000000,0.033211,0.014048,0.031029,0.000000,0.038958,0.000000,0.000000,...,0.016108,0.029983,0.089369,0.052633,0.088002,0.000000,0.000000,0.062877,1.000000,0.035400
456,0.007217,0.047029,0.025800,0.021662,0.022465,0.059090,0.064664,0.043313,0.024236,0.071827,...,0.032830,0.053526,0.000000,0.332902,0.328488,0.064501,0.429200,0.261096,0.035400,1.000000

In [21]:
# cosine similarity 값으로 
# 8조와 가장 비슷한 조를 찾기위한 과정
y_cosine = cosine_result_df[jo]
dic ={}
for i in range(len(y_cosine)):
    dic[str(posts_key[i])] = y_cosine[i]
dic = get_key(**dic)
#8조와 비슷한 조 찾기 위함
# euclidean distance 를 dic에 씌워 sorting 함(1부터 10위까지)
sorted(dic.items(), key=lambda x: x[1], reverse = True)[0:10]

[('산업안전보건법 제 24조', 1.0000000000000002),
 ('산업안전보건법 제 75조', 0.48876060704029717),
 ('산업안전보건법 제 26조', 0.4329624400536274),
 ('산업안전보건법 제 25조', 0.4328016064801411),
 ('산업안전보건법 제 116조', 0.3487751866831065),
 ('산업안전보건법 제 49조', 0.31486884853498986),
 ('화학물질관리법 제 7조', 0.3139682605734237),
 ('산업안전보건법 제 44조', 0.3097905471189142),
 ('건설기술진흥법 제 84조', 0.3041954378491575),
 ('산업안전보건법 제 22조', 0.27523802453211493)]

# CountV(Euclidean Distance)

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
vectorize = CountVectorizer(
    tokenizer=tokenizer_2, # 문장에 대한 tokenizer (위에 정의한 함수 이용)
    min_df=1,            # 단어가 출현하는 최소 문서의 개수
)

X = vectorize.fit_transform(posts)
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
# 모든 조에 해당하는 euclidean distance 를 계산
euclidean_result = []
for x in range(len(df_info)):
    tmp = []
    for y in range(len(df_info)):
        tmp.append(euclidean_distances(X[x], X[y])[0][0])
    euclidean_result.append(tmp)
# euclidean_result

In [24]:
# 모든 조에 해당하는 euclidean distance 결과 값을
# DataFrame 형태로 변환
euclidean_result_df = pd.DataFrame(euclidean_result)
euclidean_result_df

,0,1,2,3,4,5,6,7,8,9,...,447,448,449,450,451,452,453,454,455,456
0,0.000000,25.039968,8.717798,13.820275,11.135529,7.071068,9.486833,24.372115,12.083046,16.155494,...,8.246211,6.782330,6.480741,20.049938,23.832751,6.164414,14.696938,11.445523,10.000000,33.941125
1,25.039968,0.000000,24.351591,28.284271,24.103942,24.839485,26.172505,33.511192,27.147744,27.166155,...,25.980762,25.670995,25.865034,31.543621,34.073450,25.748786,28.687977,27.276363,26.438608,41.218928
2,8.717798,24.351591,0.000000,17.175564,12.409674,8.602325,10.954451,24.617067,13.638182,16.522712,...,9.055385,7.874008,8.124038,20.542639,24.372115,7.745967,15.491933,12.369317,11.224972,34.117444
3,13.820275,28.284271,17.175564,0.000000,16.401219,15.652476,17.464249,26.514147,17.691806,21.725561,...,16.643317,16.643317,16.462078,24.799194,27.622455,16.340135,20.952327,18.973666,18.138357,37.027017
4,11.135529,24.103942,12.409674,16.401219,0.000000,9.899495,13.711309,24.899799,14.832397,17.691806,...,12.727922,12.806248,12.328828,22.045408,25.219040,12.165525,17.492856,15.329710,14.628739,35.270384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,6.164414,25.748786,7.745967,16.340135,12.165525,6.928203,8.717798,24.248711,12.328828,15.716234,...,8.000000,5.291503,3.464102,19.131126,23.065125,0.000000,13.038405,9.746794,9.165151,32.893768
453,14.696938,28.687977,15.491933,20.952327,17.492856,14.899664,15.362291,27.276363,17.776389,20.420578,...,15.684387,14.212670,13.638182,14.491377,19.849433,13.038405,0.000000,10.148892,16.370706,24.738634
454,11.445523,27.276363,12.369317,18.973666,15.329710,11.958261,12.609520,25.903668,15.716234,18.493242,...,12.529964,10.908712,10.344080,15.968719,20.371549,9.746794,10.148892,0.000000,13.076697,29.478806
455,10.000000,26.438608,11.224972,18.138357,14.628739,10.488088,11.832160,25.534291,14.560220,17.748239,...,11.045361,9.486833,9.486833,20.639767,24.248711,9.165151,16.370706,13.076697,0.000000,34.234486
456,33.941125,41.218928,34.117444,37.027017,35.270384,34.000000,34.058773,39.924930,35.524639,36.235342,...,34.234486,33.406586,33.376639,25.179357,25.298221,32.893768,24.738634,29.478806,34.234486,0.000000

In [33]:
# euclidean distance 값으로 
# 8조와 가장 비슷한 조를 찾기위한 과정
y_euclidean = euclidean_result_df[jo]
dic = {}
for i in range(len(y_euclidean)):
    dic[str(posts_key[i])] = y_euclidean[i]
dic = get_key(**dic)
#8조와 비슷한 조 찾기 위함
# euclidean distance 를 dic에 씌워 sorting 함(1부터 10위까지)
sorted(dic.items(), key=lambda x: x[1])[0:10]

[('OSH24', 0.0),
 ('OSH25', 18.384776310850235),
 ('OSH49', 18.547236990991408),
 ('OSH32', 19.157244060668017),
 ('OSH35', 19.672315572906),
 ('OSH26', 19.82422760159901),
 ('OSH4', 20.0),
 ('OSH19', 20.0),
 ('OSH31', 20.808652046684813),
 ('OSH50', 20.808652046684813)]

In [26]:
cosine_result = []
for x in range(len(df_info)):
    tmp = []
    for y in range(len(df_info)):
        tmp.append(cosine_similarity(X[x], X[y])[0][0])
    cosine_result.append(tmp)

In [27]:
# 모든 조에 해당하는 cosine similarity 결과 값을
# DataFrame 형태로 변환
cosine_result_df = pd.DataFrame(cosine_result)
cosine_result_df

,0,1,2,3,4,5,6,7,8,9,...,447,448,449,450,451,452,453,454,455,456
0,1.000000,0.203186,0.052870,0.572892,0.383571,0.221470,0.047023,0.063764,0.178279,0.061602,...,0.158610,0.041996,0.046676,0.049041,0.057183,0.000000,0.041345,0.018692,0.000000,0.017168
1,0.203186,1.000000,0.306160,0.138229,0.353960,0.237855,0.085990,0.092311,0.095499,0.200266,...,0.085940,0.068264,0.009484,0.043843,0.039836,0.011790,0.036403,0.030384,0.064073,0.049997
2,0.052870,0.306160,1.000000,0.076669,0.250958,0.180656,0.000000,0.085333,0.046271,0.105523,...,0.226415,0.179847,0.066630,0.056004,0.040814,0.082832,0.039346,0.040025,0.000000,0.040844
3,0.572892,0.138229,0.076669,1.000000,0.350218,0.265085,0.083343,0.179795,0.229803,0.063524,...,0.153337,0.027067,0.045124,0.047410,0.068445,0.037398,0.035529,0.018071,0.014517,0.018441
4,0.383571,0.353960,0.250958,0.350218,1.000000,0.573409,0.121747,0.185727,0.230792,0.202025,...,0.205329,0.018122,0.100707,0.093113,0.112803,0.100157,0.101099,0.064529,0.019439,0.039510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,0.000000,0.011790,0.082832,0.037398,0.100157,0.000000,0.036835,0.037462,0.000000,0.077209,...,0.000000,0.131590,0.585018,0.230497,0.217574,1.000000,0.388650,0.322139,0.000000,0.268964
453,0.041345,0.036403,0.039346,0.035529,0.101099,0.058864,0.113734,0.050419,0.060308,0.050429,...,0.009837,0.109388,0.225788,0.675187,0.541073,0.388650,1.000000,0.688597,0.000000,0.760186
454,0.018692,0.030384,0.040025,0.018071,0.064529,0.000000,0.083063,0.036204,0.000000,0.024872,...,0.013342,0.084781,0.188457,0.584115,0.507114,0.322139,0.688597,1.000000,0.045472,0.531415
455,0.000000,0.064073,0.000000,0.014517,0.019439,0.000000,0.000000,0.009695,0.009857,0.007493,...,0.032154,0.051081,0.000000,0.095440,0.099362,0.000000,0.000000,0.045472,1.000000,0.055684
456,0.017168,0.049997,0.040844,0.018441,0.039510,0.029330,0.069022,0.073890,0.012521,0.059011,...,0.024507,0.116797,0.122601,0.668308,0.660122,0.268964,0.760186,0.531415,0.055684,1.000000

In [34]:
# cosine similarity 값으로 
# 8조와 가장 비슷한 조를 찾기위한 과정
y_cosine = cosine_result_df[jo]
dic ={}
for i in range(len(y_cosine)):
    dic[str(posts_key[i])] = y_cosine[i]
dic = get_key(**dic)
#8조와 비슷한 조 찾기 위함
# euclidean distance 를 dic에 씌워 sorting 함(1부터 10위까지)
sorted(dic.items(), key=lambda x: x[1], reverse = True)[0:10]

[('OSH24', 0.9999999999999993),
 ('OSH26', 0.803785855182591),
 ('OSH25', 0.7085036604969008),
 ('OSH49', 0.6911279493470736),
 ('OSH35', 0.6907086694181991),
 ('OSH32', 0.6561635347015473),
 ('OSH47', 0.6451447112411708),
 ('OSH19', 0.6314240248611409),
 ('OSH4', 0.6158443099086185),
 ('OSH27', 0.6147367525424573)]

In [36]:
df_data = pd.read_excel("데이터정리form.xlsx",sheet_name="안전보건법령 간")
df_data.columns = ["key",1,2,3,4,5,6,7,8,9,10]
df_data

        key    1    2    3    4   5   6   7   8   9  10
0      OSH1  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
1      OSH2  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
2      OSH3  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
3      OSH4  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
4      OSH5  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
..      ...  ...  ...  ...  ...  ..  ..  ..  ..  ..  ..
136  OSH137  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
137  OSH138  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
138  OSH139  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
139  OSH140  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN
140  OSH141  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN NaN

[141 rows x 11 columns]

In [37]:
for i in df_data.get("key"):
    print(i)

OSH1
OSH2
OSH3
OSH4
OSH5
OSH6
OSH7
OSH8
OSH9
OSH10
OSH11
OSH12
OSH13
OSH14
OSH15
OSH16
OSH17
OSH18
OSH19
OSH20
OSH21
OSH22
OSH23
OSH24
OSH25
OSH26
OSH27
OSH28
OSH29
OSH30
OSH31
OSH32
OSH33
OSH34
OSH35
OSH36
OSH37
OSH38
OSH39
OSH40
OSH41
OSH42
OSH43
OSH44
OSH45
OSH46
OSH47
OSH48
OSH49
OSH50
OSH51
OSH52
OSH53
OSH54
OSH55
OSH56
OSH57
OSH58
OSH59
OSH60
OSH61
OSH62
OSH63
OSH64
OSH65
OSH66
OSH67
OSH68
OSH69
OSH70
OSH71
OSH72
OSH73
OSH74
OSH75
OSH76
OSH77
OSH78
OSH79
OSH80
OSH81
OSH82
OSH83
OSH84
OSH85
OSH86
OSH87
OSH88
OSH89
OSH90
OSH91
OSH92
OSH93
OSH94
OSH95
OSH96
OSH97
OSH98
OSH99
OSH100
OSH101
OSH102
OSH103
OSH104
OSH105
OSH106
OSH107
OSH108
OSH109
OSH110
OSH111
OSH112
OSH113
OSH114
OSH115
OSH116
OSH117
OSH118
OSH119
OSH120
OSH121
OSH122
OSH123
OSH124
OSH125
OSH126
OSH127
OSH128
OSH129
OSH130
OSH131
OSH132
OSH133
OSH134
OSH135
OSH136
OSH137
OSH138
OSH139
OSH140
OSH141